# Generated by Django 5.1 on 2024-08-14 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupdoodles_api', '0003_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoodleCollab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doodle_collabs', to='groupdoodles_api.user')),
                ('doodle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doodle_collabs', to='groupdoodles_api.doodle')),
            ],
        ),
        migrations.AddField(
            model_name='doodle',
            name='collaborators',
            field=models.ManyToManyField(related_name='doodles', through='groupdoodles_api.DoodleCollab', to='groupdoodles_api.user'),
        ),
    ]
