# Generated by Django 5.1 on 2024-08-14 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupdoodles_api', '0004_doodlecollab_doodle_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletteLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupdoodles_api.palette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupdoodles_api.user')),
            ],
        ),
    ]
