# Generated by Django 5.1 on 2024-08-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupdoodles_api', '0005_palettelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='liked_by',
            field=models.ManyToManyField(related_name='palettes', through='groupdoodles_api.PaletteLike', to='groupdoodles_api.user'),
        ),
    ]
